package com.telegrambot.app.DTO.types;

import lombok.AllArgsConstructor;
import lombok.Getter;

@AllArgsConstructor
@Getter
public enum Currency {

    AED("United Arab Emirates Dirham", "AED"),
    AFN("Afghan Afghani", "AFN"),
    ALL("Albanian Lek", "ALL"),
    AMD("Armenian Dram", "AMD"),
    ARS("Argentine Peso", "ARS"),
    AUD("Australian Dollar", "AU$"),
    AZN("Azerbaijani Manat", "AZN"),
    BAM("Bosnia & Herzegovina Convertible Mark", "BAM"),
    BDT("Bangladeshi Taka", "BDT"),
    BGN("Bulgarian Lev", "BGN"),
    BND("Brunei Dollar", "BND"),
    BOB("Bolivian Boliviano", "BOB"),
    BRL("Brazilian Real", "R$"),
    BYN("Belarusian ruble", "BYN"),
    CAD("Canadian Dollar", "CA$"),
    CHF("Swiss Franc", "CHF"),
    CLP("Chilean Peso", "CLP"),
    CNY("Chinese Renminbi Yuan", "CN¥"),
    COP("Colombian Peso", "COP"),
    CRC("Costa Rican Colón", "CRC"),
    CZK("Czech Koruna", "CZK"),
    DKK("Danish Krone", "DKK"),
    DOP("Dominican Peso", "DOP"),
    DZD("Algerian Dinar", "DZD"),
    EGP("Egyptian Pound", "EGP"),
    ETB("Ethiopian Birr", "ETB"),
    EUR("Euro", "€"),
    GBP("British Pound", "£"),
    GEL("Georgian Lari", "GEL"),
    GTQ("Guatemalan Quetzal", "GTQ"),
    HKD("Hong Kong Dollar", "HK$"),
    HNL("Honduran Lempira", "HNL"),
    HRK("Croatian Kuna", "HRK"),
    HUF("Hungarian Forint", "HUF"),
    IDR("Indonesian Rupiah", "IDR"),
    ILS("Israeli New Sheqel", "₪"),
    INR("Indian Rupee", "₹"),
    ISK("Icelandic Króna", "ISK"),
    JMD("Jamaican Dollar", "JMD"),
    JPY("Japanese Yen", "¥"),
    KES("Kenyan Shilling", "KES"),
    KGS("Kyrgyzstani Som", "KGS"),
    KRW("South Korean Won", "₩"),
    KZT("Kazakhstani Tenge", "KZT"),
    LBP("Lebanese Pound", "LBP"),
    LKR("Sri Lankan Rupee", "LKR"),
    MAD("Moroccan Dirham", "MAD"),
    MDL("Moldovan Leu", "MDL"),
    MNT("Mongolian Tögrög", "MNT"),
    MUR("Mauritian Rupee", "MUR"),
    MVR("Maldivian Rufiyaa", "MVR"),
    MXN("Mexican Peso", "MX$"),
    MYR("Malaysian Ringgit", "MYR"),
    MZN("Mozambican Metical", "MZN"),
    NGN("Nigerian Naira", "NGN"),
    NIO("Nicaraguan Córdoba", "NIO"),
    NOK("Norwegian Krone", "NOK"),
    NPR("Nepalese Rupee", "NPR"),
    NZD("New Zealand Dollar", "NZ$"),
    PAB("Panamanian Balboa", "PAB"),
    PEN("Peruvian Nuevo Sol", "PEN"),
    PHP("Philippine Peso", "PHP"),
    PKR("Pakistani Rupee", "PKR"),
    PLN("Polish Złoty", "PLN"),
    PYG("Paraguayan Guaraní", "PYG"),
    QAR("Qatari Riyal", "QAR"),
    RON("Romanian Leu", "RON"),
    RSD("Serbian Dinar", "RSD"),
    RUB("Russian Ruble", "RUB"),
    SAR("Saudi Riyal", "SAR"),
    SEK("Swedish Krona", "SEK"),
    SGD("Singapore Dollar", "SGD"),
    THB("Thai Baht", "฿"),
    TJS("Tajikistani Somoni", "TJS"),
    TRY("Turkish Lira", "TRY"),
    TTD("Trinidad and Tobago Dollar", "TTD"),
    TWD("New Taiwan Dollar", "NT$"),
    TZS("Tanzanian Shilling", "TZS"),
    UAH("Ukrainian Hryvnia", "UAH"),
    UGX("Ugandan Shilling", "UGX"),
    USD("United States Dollar", "$"),
    UYU("Uruguayan Peso", "UYU"),
    UZS("Uzbekistani Som", "UZS"),
    VND("Vietnamese Đồng", "₫"),
    YER("Yemeni Rial", "YER"),
    ZAR("South African Rand", "ZAR");

    private final String label;
    private final String symbol;

    @Override
    public String toString() {
        return getSymbol() + "(" + getLabel() + ")";
    }
}
